Tripal Importer class
tripal/t4d8 pull request #153
Opened 2021-11-22 16:42 UTC by risharde

This is an absolute basic PR that just contains the Tripal Importer class. More PRs to come.

2021-11-22 16:43 UTC, risharde commented
Tagging @laceysanderson

2021-11-22 18:50 UTC, laceysanderson requested changes
A few deprecated functions mentioned in the review comments are to be changed but otherwise, a quick code review looks good. Once the comments are fixed, this will be ready for merge.

2021-11-22 18:50 UTC, laceysanderson commented on tripal/includes/TripalImporter.inc
> +    $import = db_select('tripal_import', 'ti')
We no longer support Drupal 8.9.x. db_select and all other db_* procedural calls have been deprecated for 9.0.x and should be replaced. The change record for this with instructions to update can be found here: https://www.drupal.org/node/2993033

2021-11-22 18:50 UTC, laceysanderson commented on tripal/includes/TripalImporter.inc
> +    $import = db_select('tripal_import', 'ti')
See deprecation comment above. Change as mentioned in https://www.drupal.org/node/2993033

2021-11-22 18:50 UTC, laceysanderson commented on tripal/includes/TripalImporter.inc
> +        drupal_set_message($tmessage, 'error');
Drupal_set_message is deprecated in 9.0.x. See https://www.drupal.org/node/2774931 for how to change.

2021-11-22 18:50 UTC, laceysanderson commented on tripal/includes/TripalImporter.inc
> +        drupal_set_message($tmessage, 'warning');
Drupal_set_message is deprecated in 9.0.x. See https://www.drupal.org/node/2774931 for how to change.

2021-11-30 04:00 UTC, risharde commented
Changes have been made though I wish there was a way to actually test this code @laceysanderson

2021-12-06 17:53 UTC, laceysanderson approved these changes
Changes according to code review look good 👍 

I changed the base of this PR to an intermediate code reviewed importer code branch.

Here's how I see this workflow going (also sent in slack):
1. For any outstanding functionality, Rish creates a new branch based on the `tv4-tripalImporterReviewed` branch, makes commits on that new branch and then creates a PR
to merge the new branch back into `tv4-tripalImporterReviewed`
2. Lacey will do a quick code review on each importer PR and once the code looks good will merge the PR
3. Once all importer functionality has made it into small PRs that were then code-reviewed and merged into `tv4-tripalImporterReviewed`, Rish can test the `tv4-tripalImporterReviewed` branch for working functionality and tests.
4. Each time Rish finds problems in the `tv4-tripalImporterReviewed` branch during testing, he will create a new small problem-focused PR similar to those in step 1.
5. Finally, once Rish feels the `tv4-tripalImporterReviewed` branch is bug-free and all problem-focused PRs are merged, Rish can create a PR merging `tv4-tripalImporterReviewed` into `9.x-4.x`.

2021-12-06 17:55 UTC, merged