Tripal Importer API functions
tripal/t4d8 pull request #154
Opened 2021-11-22 17:10 UTC by risharde

This is an absolute basic PR that just contains the Tripal Importer API functions added as an include file. More PRs to come to link everything up (those will probably need to be cherry picked so it doesn't overwrite files)

2021-11-22 17:12 UTC, risharde commented
@laceysanderson I hope this will make sense with the additional PRs which will probably be cherry picked to initialize these file additions.

2021-11-22 19:05 UTC, laceysanderson requested changes
Some deprecation notices but otherwise it looks good. Make sure your code works on 9.1.x as we no longer support 8.9.x.

2021-11-22 19:05 UTC, laceysanderson commented on tripal/src/api/tripal.importer.api.php
> + *   TRUE if the field type class file was found, FALSE otherwise.
```suggestion
 *   TRUE if the Tripal importer class file was found, FALSE otherwise.
```

2021-11-22 19:05 UTC, laceysanderson commented on tripal/src/api/tripal.importer.api.php
> +    $file_path = realpath(".") . '/' . drupal_get_path('module', $module) . '/includes/TripalImporter/' . $class . '.inc';
Should `realpath(".")` here be replaced with $DRUPAL_ROOT global variable?

drupal_get_path() is deprecated. Replace as mentioned in https://www.drupal.org/node/2940438

2021-11-30 00:46 UTC, risharde commented
I made the requested changes @laceysanderson but I messaged you a question via slack whenever you have a chance to respond. 

Sorry again for the merge happening after my change - I still have to manually specify the pull branches which slips me from time to time.

2021-12-06 18:00 UTC, laceysanderson approved these changes
Updates look good -code review ✅

2021-12-06 18:00 UTC, merged