Tripal Importer Form
tripal/t4d8 pull request #155
Opened 2021-11-22 17:43 UTC by risharde

Another basic PR with a file addition. This is the Tripal Importer Form (UI) which the future Importers will use (upcoming PR will include the importer include files)

@laceysanderson

2021-12-06 18:17 UTC, laceysanderson requested changes

2021-12-06 18:17 UTC, laceysanderson commented on tripal/src/Form/TripalImporterForm.php
> +        drupal_set_message('Cannot submit import: ' . $e->getMessage(), 'error');
drupal_set_message() is deprecated.

2021-12-06 18:17 UTC, laceysanderson commented on tripal/src/Form/TripalImporterForm.php
> +    global $user;
Deprecated: https://www.drupal.org/node/2032447

2021-12-06 18:17 UTC, laceysanderson commented on tripal/src/Form/TripalImporterForm.php
> +    // Convert the validation code into the D8/9 equivalent
Is this comment no longer correct? It looks like the code has been updated...

2021-12-06 18:17 UTC, laceysanderson commented on tripal/src/Form/TripalImporterForm.php
> +  function tripal_get_importer_form($form, &$form_state, $class) {
Are these the old D7 versions? If so, they should be removed entirely at this point.

2021-12-06 18:17 UTC, laceysanderson commented on tripal/src/Form/TripalImporterForm.php
> +  function tripal_get_importer_form_validate($form, &$form_state) {
Are these the old D7 versions? If so, they should be removed entirely at this point.

2021-12-06 18:17 UTC, laceysanderson commented on tripal/src/Form/TripalImporterForm.php
> +  function tripal_get_importer_form_submit($form, &$form_state) {
Are these the old D7 versions? If so, they should be removed entirely at this point.

2021-12-07 17:24 UTC, risharde commented
@laceysanderson thanks for reviewing, indeed you were correct - I used the old functions to create the new ones and didn't remove them. I've double checked that these functions don't seem to be in use on the form side of things so they've now been removed. Also deprecated / incompatible code removed as requested.

2021-12-07 22:28 UTC, laceysanderson approved these changes

2021-12-07 22:28 UTC, merged